config.ymlのsleepコマンドをコメントアウト

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,15 +23,15 @@ jobs:
       - checkout
       - run:
           # プライマリ コンテナは MySQL ではないため、準備が完了するまで sleep コマンドを実行します。
-          name: MySQL が準備できるまで待機
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+          # name: MySQL が準備できるまで待機
+          # command: |
+          #   for i in `seq 1 10`;
+          #   do
+          #     nc -z 127.0.0.1 3306 && echo Success && exit 0
+          #     echo -n .
+          #     sleep 1
+          #   done
+          #   echo Failed waiting for MySQL && exit 1
       - run: sudo apt update
       - run: sudo docker-php-ext-install zip pdo_mysql
       - run: sudo composer self-update
